name: Deploy to GCS + CDN

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1) Install gcloud & authenticate
      - name: Set up gcloud & authenticate
        uses: google-github-actions/setup-gcloud@v1
        with:
          # this is the one secret containing your entire JSON key
          service_account_key: ${{ secrets.GCP_AIORI_SITE_KEY }}
          # export those credentials so gsutil can see them
          export_default_credentials: true
          # explicitly set your project (optional—but avoids needing fromJson)
          project_id: aiori-f3df9

      # 2) Sync files to your bucket
      - name: Sync files to GCS
        run: |
          gsutil -m rsync -r -x '^\.github/.*$' . gs://aiori-website

      # 3) Flush any old CDN caches
      - name: Invalidate CDN cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache aiori-app-map \
            --path "/*" --global
