name: Deploy to GCS + CDN

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up GCP CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          # just your one JSON key secret
          credentials_json: ${{ secrets.GCP_AIORI_SITE_KEY }}
          # project_id is optional here—setup-gcloud will read it from the JSON.
          # If you want to be explicit (no extra secret), you can also do:
          # project_id: ${{ fromJson(secrets.GCP_AIORI_SITE_KEY).project_id }}

      - name: Sync files to GCS
        run: |
          gsutil -m rsync -r -x '^\.github/.*$' . gs://aiori-website

      - name: Invalidate CDN cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache aiori-app-map \
            --path "/*" --global

