name: Deploy to GCS + CDN

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: GCP_AIORI_SITE_KEY

      - name: Sync files to GCS
        run: |
          gsutil -m rsync -r ./public gs://aiori-website

      - name: Invalidate CDN cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache aiori-app-map \
            --path "/*" --global
